# Generated by Django 4.2.3 on 2023-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=50)),
                ('naukri', models.CharField(max_length=50)),
                ('iimjob', models.CharField(max_length=50)),
            ],
        ),
    ]
